clear all; close all;  clc;
a = imread('paisaje.jpg');
figure(1); 
imshow(a);
impixelinfo;
b = imread('RGB.png');
figure(2); 
imshow(b);
impixelinfo;
c = rgb2gray(b);
figure(3); 
imshow(c);
impixelinfo;
d = [c,c,c];
d = reshape(d, [900,900,3]);
figure(4); 
imshow(d);
impixelinfo;
e = 255-c;
figure(5); 
imshow(e);
impixelinfo;
f = 255-a;
figure(6); 
imshow(f);
impixelinfo;